#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon May 25 10:46:12 PDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim EDPtb_top_behav -key {Behavioral:edp:Functional:EDPtb_top} -tclbatch EDPtb_top.tcl -view /home/alan/kl10/edptb_behav.wcfg -log simulate.log"
xsim EDPtb_top_behav -key {Behavioral:edp:Functional:EDPtb_top} -tclbatch EDPtb_top.tcl -view /home/alan/kl10/edptb_behav.wcfg -log simulate.log

