# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks.xci
# IP: The module: 'ebox_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks.xci
# IP: The module: 'ebox_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/ebox_clocks/ebox_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebox_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
