webtalk_init -webtalk_dir /home/alan/kl10/kl10.sim/kl10pv/behav/xsim/xsim.dir/kl10pv_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb 15 00:30:27 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9bba56c6-f15d-45c5-9673-6e188d9413df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d6bd9f2d678743fd9b60b8d99f7bf270" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 2700 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1387.834 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "14 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2821544490 -regid "" -xml /home/alan/kl10/kl10.sim/kl10pv/behav/xsim/xsim.dir/kl10pv_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alan/kl10/kl10.sim/kl10pv/behav/xsim/xsim.dir/kl10pv_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alan/kl10/kl10.sim/kl10pv/behav/xsim/xsim.dir/kl10pv_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
