#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 17 12:23:59 PST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d6bd9f2d678743fd9b60b8d99f7bf270 --debug typical --relax --mt 8 -d "KL10PV_TB=1" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot kl10pv_tb_behav xil_defaultlib.kl10pv_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto d6bd9f2d678743fd9b60b8d99f7bf270 --debug typical --relax --mt 8 -d "KL10PV_TB=1" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot kl10pv_tb_behav xil_defaultlib.kl10pv_tb xil_defaultlib.glbl -log elaborate.log

