#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 17 19:35:15 PST 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim kl10pv_tb_behav -key {Behavioral:kl10pv:Functional:kl10pv_tb} -tclbatch kl10pv_tb.tcl -view /home/alan/kl10/kl10pv_tb_behav.wcfg -view /home/alan/kl10/kl10pv_tb_CLK-behav.wcfg -view /home/alan/kl10/kl10pv_tb_behav1-CRAM.wcfg -log simulate.log"
xsim kl10pv_tb_behav -key {Behavioral:kl10pv:Functional:kl10pv_tb} -tclbatch kl10pv_tb.tcl -view /home/alan/kl10/kl10pv_tb_behav.wcfg -view /home/alan/kl10/kl10pv_tb_CLK-behav.wcfg -view /home/alan/kl10/kl10pv_tb_behav1-CRAM.wcfg -log simulate.log

