#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Feb 14 23:36:46 PST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim kl10pv_tb_behav -key {Behavioral:kl10pv:Functional:kl10pv_tb} -tclbatch kl10pv_tb.tcl -view /home/alan/kl10/kl10pv_tb_behav.wcfg -view /home/alan/kl10/kl10pv_tb_CLK-behav.wcfg -log simulate.log"
xsim kl10pv_tb_behav -key {Behavioral:kl10pv:Functional:kl10pv_tb} -tclbatch kl10pv_tb.tcl -view /home/alan/kl10/kl10pv_tb_behav.wcfg -view /home/alan/kl10/kl10pv_tb_CLK-behav.wcfg -log simulate.log

