#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jan 21 17:00:14 PST 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d6bd9f2d678743fd9b60b8d99f7bf270 --incr --debug typical --relax --mt 8 -d "TESTBENCH=1" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot edptb_behav xil_defaultlib.edptb xil_defaultlib.glbl -log elaborate.log"
xelab -wto d6bd9f2d678743fd9b60b8d99f7bf270 --incr --debug typical --relax --mt 8 -d "TESTBENCH=1" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot edptb_behav xil_defaultlib.edptb xil_defaultlib.glbl -log elaborate.log

