#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Thu Jan 16 13:11:39 PST 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -L axi_vip_v1_1_6 -L processing_system7_vip_v1_0_8 -L xilinx_vip -prj top_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_6 -L processing_system7_vip_v1_0_8 -L xilinx_vip -prj top_vlog.prj 2>&1 | tee compile.log

