# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/CRAMmem/CRAMmem.xci
# IP: The module: 'CRAMmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/CRAMmem/CRAMmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CRAMmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/CRAMmem/CRAMmem.xci
# IP: The module: 'CRAMmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/kl10-fpga-rtl/kl10-fpga-rtl.srcs/sources_1/ip/CRAMmem/CRAMmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CRAMmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
